apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: test-app
    name: httpd
  name: test-app-httpd
  namespace: test-app-ns
spec:
  containers:
  - image: httpd
    name: test-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
