apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-app
    name: nginx
  name: test-app
  namespace: test-app-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-app

